print("LOG ANALYSIS:")
print("=" * 60)
print()
print("What the summary shows:")
print("- Total leads analyzed: 23,902")
print("- Total leads to drain: 12,330")
print()
print("But looking at the actual deletion:")
print("- Deduplicated 58 completed leads to 29 unique")
print()
print("The issue is in the ANALYSIS SUMMARY section of get_finished_leads():")
print()
print("It's counting ALL drain_reasons entries, including:")
print("- replied: X")
print("- completed: 11,784")  
print("- bounced_hard: X")
print("- unsubscribed: X")
print("- stale_active: X")
print("- auto_reply_detected: X")
print("- kept_active: 10,916")
print("- kept_paused: 620")
print("- kept_other: X")
print()
print("The 23,902 'analyzed' includes both DRAIN and KEEP decisions\!")
print("The 12,330 'to drain' is the sum of drain reasons")
print()
print("But the ACTUAL returned leads list only had 58 items")
print("(before deduplication to 29)")
print()
print("This suggests the API pagination worked correctly,")
print("but the counting/logging is misleading.")
