# Serena project configuration for Cold Email System

project_name: "Cold Email System"

# Primary language of the project
language: python

# Use .gitignore to automatically exclude files
ignore_all_files_in_gitignore: true

# Additional paths/patterns to ignore
ignored_paths:
  - "**/__pycache__"
  - "**/.venv"
  - "**/venv"        # add explicit venv folder ignore
  - "**/.env"
  - "**/.git"
  - "**/dist"
  - "**/build"
  - "**/node_modules"

# Allow editing by default (set to true to make read-only)
read_only: false

# List of tools to exclude (leave empty for full functionality)
excluded_tools: []

# Optional initial prompt (can stay empty, memories handle most project-specific context)
initial_prompt: ""

# Language server configuration
languages:
  python:
    lsp: pyright
    # Use the project's venv Python so `python -m pyright.langserver` works
    pythonPath: "/Users/peterlopez/Documents/Cold Email System/venv/bin/python"
    initialization_options:
      exclude:
        - "**/__pycache__"
        - "**/.venv"
        - "**/venv"
        - "**/.env"
        - "**/.git"
        - "**/dist"
        - "**/build"
        - "**/node_modules"